# Generated by Django 4.2.3 on 2023-07-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewSystem', '0002_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.ImageField(upload_to='media/')),
                ('description', models.TextField(max_length=50)),
                ('post', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
