# Generated by Django 4.2.3 on 2023-07-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewSystem', '0003_image_rename_details_detail_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.ImageField(upload_to='media/')),
                ('description', models.TextField(max_length=50)),
                ('post', models.CharField(max_length=20)),
            ],
        ),
    ]
