# Generated by Django 4.2.3 on 2023-07-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewSystem', '0004_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='url',
            field=models.ImageField(upload_to='Company_Review_System/Static/'),
        ),
    ]
