# Generated by Django 4.2.3 on 2023-07-31 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewSystem', '0005_alter_userdata_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='url',
            new_name='image',
        ),
    ]
