# Generated by Django 4.2.3 on 2023-07-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewSystem', '0006_rename_url_userdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=models.ImageField(upload_to='Company_Review_System/'),
        ),
    ]
