# Generated by Django 4.2.3 on 2023-07-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewSystem', '0007_alter_userdata_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=models.ImageField(upload_to='Static/'),
        ),
    ]
