# Generated by Django 4.2.3 on 2023-07-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewSystem', '0008_rename_url_image_image_alter_userdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
