# Generated by Django 4.2.3 on 2023-08-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewSystem', '0009_alter_userdata_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='image',
            new_name='img',
        ),
    ]
