# Generated by Django 4.2.3 on 2023-08-07 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewSystem', '0011_co'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReviewSystem.userdata'),
        ),
    ]
