# Generated by Django 4.2.3 on 2023-08-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewSystem', '0012_alter_co_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='co',
            name='nm',
            field=models.CharField(default='exit', max_length=30),
            preserve_default=False,
        ),
    ]
