# Generated by Django 4.2.3 on 2023-08-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewSystem', '0013_co_nm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Msg', models.CharField(max_length=100)),
            ],
        ),
    ]
